
name: Deploy to EC2

on:
  push:
    branches: [SpringBootCrud]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              

      - name: Build Docker Image
        run: docker build -t tekpie/springbootcrud .
        
                    
      - name: Push image to Docker Hub
        run: docker push tekpie/springbootcrud


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDrA6fQBsImECjiQiS5m45LV6P8LSXBY7qtUWrKQ/ep1AR17L2mLXi6ACj3eoKTlAxZnKDIZk+LcEuEjPhu8h8QdXHIPz9dfacSvIZaS5nkNmBwE3Wwn31m8UXhDslzcIVQ31EyxQNykQV4aNkBDAMlb8f5zGgodSMni2Q9XA9VyQ/8qQIS8q7hK4HjpUQ2z3B55ws0jNXr+QmhADYSaToQM78r1WW4LluMOUpZReHgCQWpwFOd4BLdClnqm6hCmFPEWIj6YHKDEiyaWcDY7PRn2SJbqfmDSg87gnfRDk5is6F45TZtjurQX91ShSUnvB0C2LxNXQP0mO6TTOo2yOOfIQxA/lnCo9qSpPY5G3L15v6BTHqopqdwJmDe/0mj83mhmAWXSit/mo8aw89+/TKpKYUE0kJkc2A5m9Z14aEDhVehrmNrNZF3QiLhTw3LvuKDgSOJKmAMoqG8Clk6hYs1iy32yhd5RlzLFyzMNTpDZvP/iOaNhFxEFEkWAkLz3AJVnxYKojsb2swQG/jM4guztiG67WF8ojsUASEp/y5u0MXUydifJm8vGTaHEDrYzRjgmqtG+B/8FHq4aLq0twzA4RtE2vnCNl9cAr5fS3VpVSVE0MGcXBsIho00pNzrSRcsmx3bxSeOogGdPhOGnFfI001XCFYzuNMqLd2rFZxn6Q== your_email@example.com
          script: |
            docker pull tekpie/springbootcrud:latest
            docker rm -f springbootcrud-container || true
            docker run -d -p 8080:8080 --name springbootcrud-container tekpie/springbootcrud:latest
